/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MadlibTenseNumRouteImport } from './routes/madlib.$tense.$num'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MadlibTenseNumRoute = MadlibTenseNumRouteImport.update({
  id: '/madlib/$tense/$num',
  path: '/madlib/$tense/$num',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/madlib/$tense/$num': typeof MadlibTenseNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/madlib/$tense/$num': typeof MadlibTenseNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/madlib/$tense/$num': typeof MadlibTenseNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/madlib/$tense/$num'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/madlib/$tense/$num'
  id: '__root__' | '/' | '/madlib/$tense/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MadlibTenseNumRoute: typeof MadlibTenseNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/madlib/$tense/$num': {
      id: '/madlib/$tense/$num'
      path: '/madlib/$tense/$num'
      fullPath: '/madlib/$tense/$num'
      preLoaderRoute: typeof MadlibTenseNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MadlibTenseNumRoute: MadlibTenseNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
